steps:
  # Step 1: Download dependencies
  - name: 'golang:1.21'
    entrypoint: 'go'
    args: ['mod', 'download']
    id: 'download-deps'

  # Step 2: Verify dependencies
  - name: 'golang:1.21'
    entrypoint: 'go'
    args: ['mod', 'verify']
    id: 'verify-deps'
    waitFor: ['download-deps']

  # Step 3: Run go vet
  - name: 'golang:1.21'
    entrypoint: 'go'
    args: ['vet', './...']
    id: 'vet'
    waitFor: ['verify-deps']

  # Step 4: Run gofmt check
  - name: 'golang:1.21'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if [ -n "$(gofmt -l .)" ]; then
          echo "Go files are not formatted. Please run 'gofmt -w .'"
          gofmt -l .
          exit 1
        fi
    id: 'format-check'
    waitFor: ['verify-deps']

  # Step 5: Run tests with race detector
  - name: 'golang:1.21'
    entrypoint: 'go'
    args: ['test', '-race', '-v', './...']
    id: 'test'
    waitFor: ['vet', 'format-check']

  # Step 6: Run tests with coverage
  - name: 'golang:1.21'
    entrypoint: 'go'
    args: ['test', '-coverprofile=coverage.out', '-covermode=atomic', './...']
    id: 'coverage'
    waitFor: ['test']

  # Step 7: Check coverage threshold (90%)
  - name: 'golang:1.21'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
        echo "Coverage: $COVERAGE%"
        if [ $(echo "$COVERAGE < 90" | bc) -eq 1 ]; then
          echo "Coverage is below 90%"
          exit 1
        fi
        echo "Coverage check passed!"
    id: 'coverage-check'
    waitFor: ['coverage']

  # Step 8: Build package
  - name: 'golang:1.21'
    entrypoint: 'go'
    args: ['build', '-v', './...']
    id: 'build'
    waitFor: ['coverage-check']

  # Step 9: Verify examples compile
  - name: 'golang:1.21'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        go build -v ./examples/basic
        go build -v ./examples/advanced
        go build -v ./examples/context
        go build -v ./examples/errors
    id: 'build-examples'
    waitFor: ['build']

# Optional: Publish to a Go module proxy (not implemented yet)
# This would require additional configuration and authentication

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout after 10 minutes
timeout: 600s
