# Google Cloud Build configuration for WirePusher Go SDK
#
# This configuration runs tests, builds the package, and verifies release readiness.
#
# Triggers:
# - Push to any branch: Run tests and build
# - Git tag (v*): Run tests, build, and verify release
#
# Note: Go modules are distributed via Git, not a package registry.
# Publishing is done by pushing Git tags. Users install with:
#   go get gitlab.com/wirepusher/wirepusher-go@v1.0.0
#
# No secrets required (unlike npm/PyPI).

steps:
  # Step 1: Download dependencies
  - name: 'golang:1.21'
    id: 'download-deps'
    entrypoint: 'go'
    args: ['mod', 'download']

  # Step 2: Verify dependencies
  - name: 'golang:1.21'
    id: 'verify-deps'
    entrypoint: 'go'
    args: ['mod', 'verify']
    waitFor: ['download-deps']

  # Step 3: Run gofmt check
  - name: 'golang:1.21'
    id: 'format-check'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if [ -n "$(gofmt -l .)" ]; then
          echo "❌ Go files are not formatted. Please run 'gofmt -w .'"
          gofmt -l .
          exit 1
        fi
        echo "✓ Code formatting check passed"
    waitFor: ['verify-deps']

  # Step 4: Run go vet
  - name: 'golang:1.21'
    id: 'vet'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        go vet ./...
        echo "✓ go vet check passed"
    waitFor: ['verify-deps']

  # Step 5: Run tests with race detector and coverage
  - name: 'golang:1.21'
    id: 'test'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Running tests with race detector and coverage..."
        go test -race -coverprofile=coverage.out -covermode=atomic -v ./...

        COV=$(go tool cover -func=coverage.out | grep total | awk '{print $$3}' | sed 's/%//')
        echo ""
        echo "Coverage: $$COV%"

        if [ $$(echo "$$COV < 90" | bc) -eq 1 ]; then
          echo "❌ Coverage is below 90%"
          exit 1
        fi
        echo "✓ Coverage check passed (>= 90%)"
    waitFor: ['format-check', 'vet']

  # Step 6: Build package
  - name: 'golang:1.21'
    id: 'build'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        go build -v ./...
        echo "✓ Package build successful"
    waitFor: ['test']

  # Step 7: Verify examples compile
  - name: 'golang:1.21'
    id: 'verify'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Verifying examples compile..."
        go build -v ./examples/basic
        echo "✓ basic example"
        go build -v ./examples/advanced
        echo "✓ advanced example"
        go build -v ./examples/context
        echo "✓ context example"
        go build -v ./examples/errors
        echo "✓ errors example"
        go build -v ./examples/encryption
        echo "✓ encryption example"
        echo ""
        echo "✅ All examples compile successfully!"
    waitFor: ['build']

  # Step 8: Verify release (only on Git tags)
  - name: 'golang:1.21'
    id: 'release'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if [ "$TAG_NAME" != "" ]; then
          echo "Git tag detected: $TAG_NAME"
          echo ""
          echo "Verifying release readiness..."

          # Verify tag format
          if echo "$TAG_NAME" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+'; then
            echo "✓ Tag format is valid: $TAG_NAME"
          else
            echo "❌ Invalid tag format. Expected: v1.2.3"
            exit 1
          fi

          # Check required files
          test -f go.mod && echo "✓ go.mod exists" || exit 1
          test -f go.sum && echo "✓ go.sum exists" || exit 1
          test -f README.md && echo "✓ README.md exists" || exit 1
          test -f LICENSE && echo "✓ LICENSE exists" || exit 1

          echo ""
          echo "✅ Release verification complete for $TAG_NAME"
          echo ""
          echo "Go module is now available via:"
          echo "  go get gitlab.com/wirepusher/wirepusher-go@$TAG_NAME"
        else
          echo "No Git tag detected. Skipping release verification."
          echo "To release, push a Git tag: git tag v1.0.0 && git push origin v1.0.0"
        fi
    waitFor: ['verify']

  # Step 9: Send notification on successful release (only on tags)
  - name: 'curlimages/curl:latest'
    id: 'notify-release'
    waitFor: ['release']
    entrypoint: 'sh'
    secretEnv: ['WIREPUSHER_TOKEN']
    args:
      - '-c'
      - |
        if [ -z "$TAG_NAME" ]; then
          echo "=== No Git tag detected ==="
          echo "Skipping notification (only runs on tags)"
          exit 0
        fi

        echo "=== Sending release notification via NotifAI ==="
        curl -s -X POST https://api.wirepusher.dev/notifai \
          -H "Authorization: Bearer $$WIREPUSHER_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{
            \"text\": \"WirePusher Go SDK $TAG_NAME released successfully. Install via go get gitlab.com/wirepusher/wirepusher-go@$TAG_NAME. View release at https://gitlab.com/wirepusher/wirepusher-go/-/tags/$TAG_NAME\"
          }"

        echo ""
        echo "✓ Release notification sent via NotifAI"

# Secrets for release notifications
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/wirepusher-token/versions/latest
      env: 'WIREPUSHER_TOKEN'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true

# Timeout (10 minutes should be plenty)
timeout: '600s'

# Build artifacts
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_cloudbuild/artifacts/go-sdk/${BUILD_ID}'
    paths:
      - 'coverage.out'
      - 'go.mod'
      - 'README.md'
